# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.1.5
maven_group=net.nerdorg.minehop
archives_base_name=minehop

# Dependencies
fabric_version=0.155.3+26.1.2
cloth_version=26.1.154
modmenu_version=18.0.2